"""rev

Revision ID: 5ce45db748ea
Revises: a914fbfb963b
Create Date: 2024-08-09 10:31:39.872430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce45db748ea'
down_revision: Union[str, None] = 'a914fbfb963b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_data', sa.Column('file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_data', 'file')
    # ### end Alembic commands ###
