"""rev

Revision ID: 60437ab6bcd6
Revises: 2dcb860c8aa8
Create Date: 2024-08-05 13:44:10.679333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60437ab6bcd6'
down_revision: Union[str, None] = '2dcb860c8aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'image', ['image'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='unique')
    # ### end Alembic commands ###
