"""rev

Revision ID: e989204a3030
Revises: 50416f77405c
Create Date: 2024-08-09 08:15:48.408627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e989204a3030'
down_revision: Union[str, None] = '50416f77405c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_id', table_name='role')
    op.drop_index('role', table_name='role')
    op.drop_table('role')
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('admin', 'user'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.ENUM('admin', 'user'),
               nullable=True)
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('role', 'role', ['role'], unique=True)
    op.create_index('ix_role_id', 'role', ['id'], unique=False)
    # ### end Alembic commands ###
