"""rev

Revision ID: fe9ee8b75d76
Revises: e989204a3030
Create Date: 2024-08-09 09:04:11.883474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe9ee8b75d76'
down_revision: Union[str, None] = 'e989204a3030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_data', 'origin_filepath')
    op.drop_column('master_data', 'thumbnail_filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_data', sa.Column('thumbnail_filepath', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('master_data', sa.Column('origin_filepath', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
